# Generated by Django 5.2.16 on 2026-07-30 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_ticketcategory_category_per_user_limit_at_least_one'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked in')], db_index=True, default='issued', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.ticketcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-issued_at',),
                'indexes': [models.Index(fields=['category', 'status'], name='ticket_category_status_idx'), models.Index(fields=['user', 'status'], name='ticket_user_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', True), ('checked_in_at__isnull', True), ('status', 'issued')), models.Q(('cancelled_at__isnull', False), ('checked_in_at__isnull', True), ('status', 'cancelled')), models.Q(('cancelled_at__isnull', True), ('checked_in_at__isnull', False), ('status', 'checked_in')), _connector='OR'), name='ticket_status_timestamps_consistent')],
            },
        ),
    ]
