# Generated by Django 5.2.16 on 2026-07-27 11:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=250)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('registration_opens_at', models.DateTimeField()),
                ('registration_closes_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('starts_at', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='event_end_after_start'), models.CheckConstraint(condition=models.Q(('registration_closes_at__gt', models.F('registration_opens_at'))), name='event_registration_close_after_open')],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField()),
                ('per_user_limit', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('registration_opens_at', models.DateTimeField(blank=True, help_text='Leave empty to use the event registration opening time.', null=True)),
                ('registration_closes_at', models.DateTimeField(blank=True, help_text='Leave empty to use the event registration closing time.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='events.event')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('event', 'slug'), name='unique_ticket_category_slug_per_event'), models.CheckConstraint(condition=models.Q(('registration_opens_at__isnull', True), ('registration_closes_at__isnull', True), ('registration_closes_at__gt', models.F('registration_opens_at')), _connector='OR'), name='category_registration_close_after_open')],
            },
        ),
    ]
