# Generated by Django 5.2.16 on 2026-07-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
    ]
