# Generated by Django 5.2.16 on 2026-07-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_slug_alter_ticketcategory_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticketcategory',
            constraint=models.CheckConstraint(condition=models.Q(('per_user_limit__gte', 1)), name='category_per_user_limit_at_least_one'),
        ),
    ]
